services:
  backend_prod:
    profiles:
      - prod
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: prod
    container_name: paprika_backend_prod
    volumes: []
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env.production
    restart: unless-stopped
